name: Build & Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  packages: write    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
      - name: Descargar código
        uses: actions/checkout@v4

      - name: comprobar codigo backend
        run: |
         cd app
         python -m pip install --upgrade pip
         pip install fastapi uvicorn httpx
         python -m py_compile main.py 

      - name: comprobar codigo frontend
        run: |
         cd frontend
         npm install
         CI=false npm run build

      - name: Login en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ───── BACKEND ─────
      - name: Build backend
        run: docker build -t ghcr.io/${{ github.repository_owner }}/aurum-backend:latest ./app

      - name: Push backend
        if: github.event_name != 'pull_request'
        run: docker push ghcr.io/${{ github.repository_owner }}/aurum-backend:latest

      - name: Comprobar seguridad Backend
        run: |
          cd app
          pip install --upgrade pip
          pip install fastapi uvicorn httpx
          python -m py_compile main.py 

      - name: Montar contenedor Backend
        run: |
            docker run -d -p 8000:8000 --name backend ghcr.io/${{ github.repository_owner }}/aurum-backend:latest
            sleep 30
            curl --fail http://localhost:8000/health
            docker stop backend || true
            docker rm backend || true

      # ───── FRONTEND ─────
      - name: Build frontend
        run: docker build -t ghcr.io/${{ github.repository_owner }}/aurum-frontend:latest ./frontend
             

      - name: Push frontend
        if: github.event_name != 'pull_request'
        run: docker push ghcr.io/${{ github.repository_owner }}/aurum-frontend:latest

      - name: Comprobar seguridad Frontend
        run: | 
          cd frontend    
          npm ci
          npm audit --audit-level=high || true


      - name: Montar contenedor Frontend
        run: |
          docker run -d -p 3000:80 --name frontend ghcr.io/${{ github.repository_owner }}/aurum-frontend:latest
          sleep 30

          echo "=== STATUS ==="
          docker ps -a

          echo "=== LOGS FRONTEND ==="
          docker logs frontend

          echo "=== TEST LOOP ==="
           for i in {1..20}; do
           echo "intentando curl..."
           curl -v http://localhost:3000 && break
          sleep 2
          done